### ISSUE TITLE
A new release?

### ISSUE THREAD

**Issue by azmeuk** [fief-dev/zxcvbn-rs-py#4]
Hi,
Is there something preventing the publication of a new release with the latest PyO3 changes?
This would be much appreciated for bringing Python 3.13 support in production :pray:

Thank you for your hard work :bow:

**Comment by frankie567** [comment]
Done ✨ https://pypi.org/project/zxcvbn-rs-py/0.2.0/

**Comment by azmeuk** [comment]
Thank you for your reactivity. :bow:
